Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
Users:
- Arn: arn:aws:iam::540373086296:user/brandon@madhattertech.ca
  CreateDate: '2020-04-09T19:13:52+00:00'
  PasswordLastUsed: '2020-04-13T21:57:09+00:00'
  Path: /
  UserId: AIDAX3UF66BMO3ESKWNXH
  UserName: brandon@madhattertech.ca
- Arn: arn:aws:iam::540373086296:user/deployment@madhattertech.ca
  CreateDate: '2020-04-13T23:41:31+00:00'
  Path: /
  UserId: AIDAX3UF66BMPM53ZVDLB
  UserName: deployment@madhattertech.ca
