name: MadHatter Continuous Deployment

on: 
  push:
    branches:
      - master
        
env:
  # the AWS credentials for the staging organization
  AWS_ACCESS_KEY_ID_PRODUCTION: ${{ secrets.AwsAccessKeyIdProduction }}
  AWS_SECRET_ACCESS_KEY_PRODUCTION: ${{ secrets.AwsSecretAccessKeyProduction }}
  
  # the AWS credentials for the staging organization
  AWS_ACCESS_KEY_ID_STAGING: ${{ secrets.AwsAccessKeyIdStaging }}
  AWS_SECRET_ACCESS_KEY_STAGING: ${{ secrets.AwsSecretAccessKeyStaging }}

jobs:
  aws_production_environment_setup:
    name: AWS Production Environment Setup
    runs-on: ubuntu-latest
    steps:

    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Install YAML Parser
      run: sudo snap install yq
      shell: bash

    - name: Install AWS CLI
      run: sh ./.github/scripts/aws/install-cli.sh
      shell: bash

    - name: Configure AWS CLI
      run: sh ./.github/scripts/aws/configure-cli.sh
      shell: bash

      #- name: Create AWS Networking 
      #run: sh ./.github/scripts/aws/create-network.sh
      #shell: bash

      #- name: Create Key Pair
      #run: sh ./.github/scripts/aws/create-key-pair.sh
      #shell: bash

      #- name: Create EC2 Instance
      #run: sh ./.github/scripts/aws/create-ec2-instance.sh
      # shell: bash
    - name: Create issue using REST API
      run: echo ${{ secrets.public-key }}
